-- Writer: Young-Kyoon Suh (yksuh@cs.arizona.edu)
-- Date: 04/19/14
-- Description: Drop tables for DBMS thrashing study

DROP TABLE AZDBLAB_BATCHSET CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_BATCHSETHASPARAMETER CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_COMPLETEDFGTASK CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_BSSATISFIESASPECT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_BATCH CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_BATCHHASRESULT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_CLIENT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_CLIENTHASRESULT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_TRANSACTION CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_TRANSACTIONHASRESULT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_STATEMENT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_STATEMENTHASRESULT CASCADE CONSTRAINTS;
