-- Writer: Young-Kyoon Suh (yksuh@cs.arizona.edu)
-- Date: 04/19/14 (v1.0), 05/07/14 (v2.0)
-- Description: Drop tables for DBMS thrashing study

DROP TABLE AZDBLAB_BATCHSET CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_BATCH CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_CLIENT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_TRANSACTION CASCADE CONSTRAINTS;
--DROP TABLE AZDBLAB_STATEMENT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_BATCHSETHASRESULT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_BATCHHASRESULT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_CLIENTHASRESULT CASCADE CONSTRAINTS;
DROP TABLE AZDBLAB_TRANSACTIONHASRESULT CASCADE CONSTRAINTS;
--DROP TABLE AZDBLAB_BSSATISFIESASPECT CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_BATCHSET;
DROP SEQUENCE SEQ_BATCH;
DROP SEQUENCE SEQ_CLIENT;
DROP SEQUENCE SEQ_TRANSACTION;

DROP SEQUENCE SEQ_BATCHSETRESULT;
DROP SEQUENCE SEQ_BATCHRESULT;
DROP SEQUENCE SEQ_CLIENTRESULT;
DROP SEQUENCE SEQ_XACTRESULT;

--DROP TABLE AZDBLAB_COMPLETEDFGTASK CASCADE CONSTRAINTS;
D--ROP TABLE AZDBLAB_BSSATISFIESASPECT CASCADE CONSTRAINTS;

--SELECT SEQ_BATCHSETRESULT .NEXTVAL FROM DUAL;
--SELECT SEQ_BATCHRESULT .NEXTVAL FROM DUAL;
--SELECT SEQ_BATCHSET .NEXTVAL FROM DUAL;
--SELECT SEQ_BATCH .NEXTVAL FROM DUAL;
