#!/bin/sh

if [ "$1" = 0  ]; then

 echo $1 > /proc/sys/vm/drop_caches

elif [ "$1" = 1  ]; then

 echo $1 > /proc/sys/vm/drop_caches

elif [ "$1" = 2  ]; then

 echo $1 > /proc/sys/vm/drop_caches

elif [ "$1" = 3  ]; then

 echo $1 > /proc/sys/vm/drop_caches

else

  echo usage: setdropcaches  [ 0, 1, 2, or 3]
  exit 1

fi

exit 0
