############################################
########## read ##########################
############################################
x = rbind(db2)
med.fit <- lm(ATP ~ NUMPROCESSORS + PK, data = x)
out.fit <- lm(MAXMPL ~ PK + ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)
x = rbind(mysql)
med.fit <- lm(ATP ~ NUMPROCESSORS + PK, data = x)
out.fit <- lm(MAXMPL ~ PK + ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)
x = rbind(oracle)
med.fit <- lm(ATP ~ NUMPROCESSORS + PK, data = x)
out.fit <- lm(MAXMPL ~ PK + ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)
x = rbind(pgsql)
med.fit <- lm(ATP ~ NUMPROCESSORS + PK, data = x)
out.fit <- lm(MAXMPL ~ PK + ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)
x = rbind(sqlserver)
med.fit <- lm(ATP ~ NUMPROCESSORS + PK, data = x)
out.fit <- lm(MAXMPL ~ PK + ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)

############################################
########## update ##########################
############################################
x = rbind(db2)
med.fit <- lm(ATP ~ NUMPROCESSORS, data = x)
out.fit <- lm(MAXMPL ~ ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)
x = rbind(mysql)
med.fit <- lm(ATP ~ NUMPROCESSORS, data = x)
out.fit <- lm(MAXMPL ~ ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)
x = rbind(oracle)
med.fit <- lm(ATP ~ NUMPROCESSORS, data = x)
out.fit <- lm(MAXMPL ~ ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)
x = rbind(pgsql)
med.fit <- lm(ATP ~ NUMPROCESSORS, data = x)
out.fit <- lm(MAXMPL ~ ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)
x = rbind(sqlserver)
med.fit <- lm(ATP ~ NUMPROCESSORS, data = x)
out.fit <- lm(MAXMPL ~ ATP + NUMPROCESSORS, data = x)
durbinWatsonTest(med.fit)
durbinWatsonTest(out.fit)
